---
- name: Change acess token  for inventory
  hosts: localhost
  gather_facts: false
  vars:
    inventory_hostname_short: esassvansible02
    gcp_ce_machine_type: e2-micro
    gcp_ce_zone: europe-west1-b
    #gcp_ce_project_name: ats-gcp-shared-mgmt #No reconoce el nombre cambiado
    gcp_ce_project_name: acciona-cpd-service
  tasks:
    - name: obtain Access token from your session
      command: gcloud auth print-access-token
      register: access_token_value

        #- debug: msg=Token  is {{  access_token_value  }}

    - name: Ensure  is set to enforcing mode
      ansible.builtin.lineinfile:
        path:  inventory/gcp.yaml
        regexp: '^access_token:'
        line:  'access_token: " "{{  access_token_value.stdout }}" "'




