---
- name: Info  GCP instance
  hosts: localhost
  gather_facts: false
  vars:
    inventory_hostname_short: esassvansible02
    gcp_ce_machine_type: e2-micro
    gcp_ce_zone: europe-west1-b
    #gcp_ce_project_name: ats-gcp-shared-mgmt #No reconoce el nombre cambiado
    gcp_ce_project_name: acciona-cpd-service
  tasks:
    - name: obtain Access token from your session
      command: gcloud auth print-access-token
      register: access_token_value
       #- debug: msg=Token  is {{  access_token_value  }}

    - name: Get info of  a GCP VM instance
      gcp_compute_instance_info:
        auth_kind: accesstoken
        access_token: "{{ access_token_value.stdout }}"  
        zone: "{{ gcp_ce_zone }}" 
        filters:
          - name =   "{{  inventory_hostname_short }}"
        project:  "{{ gcp_ce_project_name }}"
      register: vminfo_value
      delegate_to: localhost
    - debug: msg=Info   is {{  vminfo_value  }}

